

export const cuisinesList =[
    "American",
    "Asian",
    "Bakery",
    "Barbecue",
    "Beverages",
    "Burgers",
    "Cafe",
    "Chinese",
    "Coffee",
    "Desserts",
    "Fast Food",
    "Healthy",
    "Ice Cream",
    "Indian",
    "Italian",
    "Japanese",
    "Juices",
    "Korean",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Pizza",
    "Salad",
    "Sandwiches",
    "Seafood",
    "Sushi",
    "Thai",
    "Vegetarian",
    "Vietnamese",
    "Other",
]